// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
void ui_event_mole( lv_event_t * e);
extern lv_obj_t *ui_mole1;
extern lv_obj_t *ui_mole2;
extern lv_obj_t *ui_mole3;
extern lv_obj_t *ui_mole4;
extern lv_obj_t *ui_mole5;
extern lv_obj_t *ui_mole6;
extern lv_obj_t *ui_hit;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Score;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_back2_png);   // assets/back2.png
LV_IMG_DECLARE( ui_img_1881230945);   // assets/mole-2.png
LV_IMG_DECLARE( ui_img_1253162907);   // assets/hit-2.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
