// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include "lvgl.h"
#include "ui_helpers.h"


void showMole(int moleHole);
void hideMole();
void showMoles(void * param);

/**********************
 *  STATIC VARIABLES
 **********************/

static char hole[6] = {0, 0, 0, 0, 0, 0};


//score
int score = 0;

void hitFunction(lv_event_t * e)
{
	//increase score
	score++;
	//make label 1 show score
	//convert score to string
	char score_str[12];
	sprintf(score_str, "%d", score);
      _ui_label_set_property(ui_Score, _UI_LABEL_PROPERTY_TEXT, score_str);
	lv_obj_add_flag( lv_event_get_target(e), LV_OBJ_FLAG_HIDDEN );
}
void startGame(lv_event_t * e)
{
	_ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "started");

    // Initialize the random number generator
    srand(time(NULL));

    // Start a timer for 2 seconds
    lv_timer_t * timer = lv_timer_create(showMoles, 1000, NULL);
    lv_timer_ready(timer);
}

void showMoles(void * param)
{
    // Hide all moles
    hideMole();

    // Randomize the number of moles to show (1-3)
    int numMoles = (rand() % 3) + 1;

    for(int i = 0; i < numMoles; i++) {
        // Randomize the mole position
        int moleHole = rand() % 6;
        // do {
        //     moleHole = rand() % 6; // Generate a random number between 0 and 5
        // } while(hole[moleHole] == 1);

        // Show the mole in the selected hole
        showMole(moleHole);
    }
}

void showMole(int moleHole)
{
    switch(moleHole){
		case 0:
			 _ui_flag_modify( ui_mole1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
			hole[0] = 1;
			break;
		case 1:
			 _ui_flag_modify( ui_mole2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
			hole[1] = 1;
			break;
		case 2:
			 _ui_flag_modify( ui_mole3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
			hole[2] = 1;
			break;
		case 3:
			 _ui_flag_modify( ui_mole4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
			hole[3] = 1;
			break;
		case 4:
			_ui_flag_modify( ui_mole5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
			hole[4] = 1;
			break;
		case 5:
			_ui_flag_modify( ui_mole6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
			hole[5] = 1;
			break;
		default:
	}
}



void hideMole()
{
	_ui_flag_modify( ui_mole1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
	_ui_flag_modify( ui_mole2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
	_ui_flag_modify( ui_mole3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
	_ui_flag_modify( ui_mole4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
	_ui_flag_modify( ui_mole5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
	_ui_flag_modify( ui_mole6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);

	//make the moleArray all 0
	for(int i = 0; i < 6; i++) {
		hole[i] = 0;
	}


}
